[build]
target = "arduboy.json"
target-dir = "./target"

[profile.release]
codegen-units = 1
lto = "fat"
strip = true
opt-level = "z"
panic = "abort"

[profile.dev]
codegen-units = 1
lto = "fat"
strip = true
opt-level = "z"
panic = "abort"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
